#!/bin/bash

WD="`dirname "$0"`"

if [ ! -x "$WD/main" ]
then
	make -C "$WD" main || exit $?
fi

if [ "`uname -s`" == "Darwin" ]
then
	DYLD_LIBRARY_PATH="$WD/fstitch/obj/kernel/lib:$WD:$DYLD_LIBRARY_PATH" exec "$WD/main"
else
	LD_LIBRARY_PATH="$WD/fstitch/obj/kernel/lib:$LD_LIBRARY_PATH" exec "$WD/main"
fi
