#!/bin/bash

[ -f .copy_to_kudos -a ! -f .copy_to ] && mv .copy_to_kudos .copy_to

if [ ! -f .copy_to ]
then
	echo "No .copy_to file."
	echo -n "Please enter target directory: "
	read TARGET
	echo "$TARGET" > .copy_to
fi

TARGET="`cat .copy_to`"

function arg_error() {
	echo "Usage: `basename "$0"` <machine>" 1>&2
	exit 1
}

if [ $# -ne 1 ]; then arg_error "$0"; fi

MACHINE=$1.cs.ucla.edu
if ! host $MACHINE > /dev/null
then
	MACHINE=kudos-$1.cs.ucla.edu
	host $MACHINE > /dev/null || arg_error "$0"
fi

rsync --rsh=ssh -vaSz --exclude=*.o \
	--exclude=/main --exclude=/core \
	--exclude=/tags --exclude=/php/ \
	--exclude=/fstitch --exclude=/.depend \
	--exclude=/.toilet_history \
	--exclude=/libtoilet.so --exclude=/io_count.so \
	--exclude=.*.swp --exclude=.*.swo --exclude=.*.swn \
	. $MACHINE:$TARGET/
