#!/bin/bash

cd "`dirname "$0"`"

rm -rf .deps .libs Makefile Makefile.fragments Makefile.global \
       Makefile.objects acinclude.m4 aclocal.m4 autom4te.cache build \
       config.guess config.h config.h.in config.log config.nice config.status \
       config.sub configure configure.in include install-sh libtool ltmain.sh \
       missing mkinstalldirs modules php_toilet.lo run-tests.php toilet.la
