#!/bin/bash

# This PHP module was created by following the very nice instructions at
# http://devzone.zend.com/node/view/id/1021, and then learning the rest of
# the magic by reading existing code. (Unfortunately the aforementioned
# tutorial stops just a tad short of where you'd ideally like it to.)

set -e
set -x

phpize
./configure
make
